export const actions = {
    ADICIONAR_NUMERO_REQUESTED: 'ADICIONAR_NUMERO_REQUESTED',
    ADICIONAR_NUMERO_SUCCEEDED: 'ADICIONAR_NUMERO_SUCCEEDED',
    ADICIONAR_NUMERO_FAILED: ' ADICIONAR_NUMERO_FAILED',
    MULTIPLICAR_NUMERO_REQUESTED: 'MULTIPLICAR_NUMERO_REQUESTED',
    MULTIPLICAR_NUMERO_SUCCEEDED: 'MULTIPLICAR_NUMERO_SUCCEEDED',
    MULTIPLICAR_NUMERO_FAILED: ' ADICIONAR_NUMERO_FAILED',
}